### ISSUE TITLE
Slack user id format with name

### ISSUE THREAD

**Issue by vktr** [nubot/nubot#10]
We support the Slack message format for users, ie. `<@userid>` which is replaced with `@username`, however Slack can also send `<@userid|name>` which we currently fail to replace.

The SlackAdapter keeps a cache of the connected users, so we should be able to ignore whatever's on the right side of the pipe and just allow it to exist and replace it like currently do.

**Comment by patriksvensson** [comment]
Pretty sure this one is fixed for some reason. Did you fix it and forgot to close the issue?

**Comment by vktr** [comment]
I don't think it's fixed - I just haven't had Slack send me those other types of formatted messages :smile: They exist according to the documentation which was why I opened this issue.
